language: go

go:
  - 1.8.x

services:
  - docker

before_install:
  - set -e

script:
  - make
  - tar xfvz build/mqtt_blackbox_exporter-*.linux-amd64.tar.gz
  - make test

after_success:
  - |
    [[ (-z "${TRAVIS_TAG?}" && "${TRAVIS_BRANCH?}" != master) || "${TRAVIS_PULL_REQUEST?}" == "true" ]] && exit 0;
    docker login -u "${DOCKER_USERNAME?}" -p "${DOCKER_PASSWORD?}";
    docker build -t "${DOCKER_BUILD_IMAGE?}";

    version=""
    if [[ -n "${TRAVIS_TAG?}" ]]; then
      version="${TRAVIS_TAG?}"
    else
      version="$(cat VERSION | tr -d '\n')-${TRAVIS_COMMIT:0:7}";
    fi

    docker tag "${DOCKER_BUILD_IMAGE?}" "${DOCKER_BUILD_IMAGE?}:${version?}";
    docker push "${DOCKER_BUILD_IMAGE?}:${version?}";
